apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: thetwaihtut/solar-system:5-7c3b2fba7d32d9c9235b2c9956d3c0193c25b62d
        name: solar-system
        imagePullPolicy: Always
        ports: 
        - containerPort: 80
