apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
  namespace: staging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: thetwaihtut/solar-system:3-79d6f25d0d8ff825ffcfb49d0c2f6df8f197e457
        name: solar-system
        imagePullPolicy: Always
        ports: 
        - containerPort: 80
